GET http://localhost:3000/events


###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "New Event",
  "description": " asd as d",
  "date": "2017-01-01T00:00:00",
  "price": 187
}

###
@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3000/events/{{ eventId }}

###
PATCH http://localhost:3000/events/{{ eventId }}
Content-Type: application/json

{
  "name": "New Event",
  "description": "Description of new event",
  "date": "2019-01-01T00:00:00",
  "price": 187
}

###
DELETE http://localhost:3000/events/{{ eventId }}



###
GET http://localhost:3000/events/{{ eventId }}/spots

###
DELETE http://localhost:3000/events/{{ eventId }}

###
# @name createSpot
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": "A6"
}
###
@spotName = {{ createSpot.response.body.name }}


POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json

{
  //"spots": ["{{ spotName }}"],
  "spots": ["{{ spotName }}"],
  "ticket_kind": "full",
  "email": "test@test.com"
}